### ISSUE TITLE
Is Nvidia Graphic Card the must option to run the demo?

### ISSUE THREAD

**Issue by iotcg** [ApolloAuto/ApolloAuto.github.io#5]
After checking script:apollo/scripts/apollo_base.sh, it seems that nvidia graphic card is the must needed to run the demo? Is it true? Does it have plan to support other vendor's card?
  161   # setup nvidia device
  162   sudo /sbin/modprobe nvidia
  163   sudo /sbin/modprobe nvidia-uvm
  164   if [ ! -e /dev/nvidia0 ];then
  165     sudo mknod -m 666 /dev/nvidia0 c 195 0
  166   fi
  167   if [ ! -e /dev/nvidiactl ];then
  168     sudo mknod -m 666 /dev/nvidiactl c 195 255
  169   fi
  170   if [ ! -e /dev/nvidia-uvm ];then
  171     sudo mknod -m 666 /dev/nvidia-uvm c 243 0
  172   fi
  173   if [ ! -e /dev/nvidia-uvm-tools ];then
  174     sudo mknod -m 666 /dev/nvidia-uvm-tools c 243 1
  175   fi
  176 
  177   if [ ! -e /dev/nvidia-uvm-tools ];then
  178     sudo mknod -m 666 /dev/nvidia-uvm-tools c 243 1
  179   fi

**Comment by jinghaomiao** [comment]
No it's not needed.
